routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('login');
});
Route::get('administrator/login', ['uses' => 'Auth\AuthsController@getLogin'])->name('login');
Route::post('administrator/login', ['uses' => 'Auth\AuthsController@postLogin'])->name('login.post');
Route::post('administrator/register', ['uses' => 'Auth\AuthsController@postRegister'])->name('register');
Route::get('administrator/logout', ['uses' => 'Auth\AuthsController@getLogout'])->name('logout');
Route::get('user/activation/{token}', 'Auth\AuthsController@getActiveUser')->name('user.activate');
Route::post('user/forgot', 'Auth\AuthsController@postForgot')->name('user.forgot');
Route::get('/reset-password/{token}', 'Auth\AuthsController@getResetPassword')->name('user.reset');
Route::post('/reset-password', 'Auth\AuthsController@postResetPassword')->name('user.post-reset');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function () {
    Route::group(['prefix' => 'system'], function () {
        Route::resource('position', Systems\PositionsController::class);
        Route::get('user/user-department/{id}', 'Users\UsersController@getUserByDepartment')->name('user.list-user-by-department');
        Route::post('user/import', 'Users\UsersController@postImport')->name('user.import');
        Route::post('role/import', 'Permissions\RolesController@postImport')->name('role.import');
        Route::post('user/change-password', 'Users\UsersController@postChangePassword')->name('user.post-change-password');
        Route::get('/user/list', 'Users\UsersController@getList');
        Route::get('/user/change-password', 'Users\UsersController@getChangePassword')->name('user.get-change-password');
        Route::get('/user/be-managed', 'Users\UsersController@getBeManaged');
        Route::get('/user/search', 'Users\UsersController@getSearch');
        Route::post('/user/{id}', 'Users\UsersController@destroy');
        Route::get('/user/read-notification/{id}', 'Users\UsersController@readNotification')->name('user.read.notification');
        Route::get('/user/get-structure/{company}', 'Users\UsersController@getStructureByCompany')->name('user.get-structure');
        Route::resource('user', Users\UsersController::class);

        Route::post('company/{company}/structure/post-index', 'Systems\StructureCompaniesController@postIndex')->name('structure.post-index');
        Route::post('company/{company}/structure/delete', 'Systems\StructureCompaniesController@postDelete')->name('structure.delete');
        Route::get('company/{company}/structure/edit/{id}', 'Systems\StructureCompaniesController@getEdit');
        Route::post('company/{company}/structure/edit', 'Systems\StructureCompaniesController@postEdit')->name('structure.edit-post');
        Route::get('company/{company}/structure', 'Systems\StructureCompaniesController@index')->name('structure.index');
        Route::post('company/{company}/structure', 'Systems\StructureCompaniesController@store')->name('structure.store');
        Route::post('/company/attachment', 'Systems\CompaniesController@postUploadAttachment')->name('company.upload-attachment');
        Route::delete('/company/attachment', 'Systems\CompaniesController@postDeleteAttachment')->name('company.delete-attachment');
        Route::resource('company', Systems\CompaniesController::class);
        Route::resource('role', Permissions\RolesController::class);
        Route::resource('permission', Permissions\PermissionsController::class);
        Route::get('/config-role', 'Permissions\RolesController@getConfigRole')->name('role.config-role');
        Route::put('/put-permission', 'Permissions\RolesController@putPermissionIntoRole')->name('role.put-permission');
        Route::put('put-role', 'Permissions\RolesController@putRoleIntoUser')->name('role.put-role');
        Route::get('config-user', 'Permissions\RolesController@getConfigUser')->name('role.config-user');
        Route::get('permission-by-role', 'Permissions\RolesController@getPermissionByRole');
    });
    Route::group(['prefix' => 'asset'], function () {
        Route::get('district/{id}', 'Partners\PartnersController@getDistrictOnCity')->name('city.district.list');
        Route::get('dashboard', 'Assets\DashboardController@index')->name('asset.index');
        Route::post('/contract/attachment', 'Contracts\ContractsController@postUploadAttachment')->name('contract.upload-attachment');
        Route::delete('/contract/attachment', 'Contracts\ContractsController@postDeleteAttachment')->name('contract.delete-attachment');
        Route::post('/partner/attachment', 'Partners\PartnersController@postUploadAttachment')->name('partner.upload-attachment');
        Route::delete('/partner/attachment', 'Partners\PartnersController@postDeleteAttachment')->name('partner.delete-attachment');
        Route::get('/partner/download-file/{id}', 'Partners\PartnersController@downloadFile')->name('partner_stores.download');
        Route::post('/assets/attachment', 'Assets\AssetsController@postUploadAttachment')->name('asset.upload-attachment');
        Route::delete('/assets/attachment', 'Assets\AssetsController@postDeleteAttachment')->name('asset.delete-attachment');
        Route::get('/partner/search-partner', 'Partners\PartnersController@searchPartner')->name('partner.search-partner');
        Route::get('/contract/search-contract', 'Contracts\ContractsController@searchContract')->name('contract.search-contract');
        Route::get('/contract/partner-contract/{id}', 'Contracts\ContractsController@getPartnerContract')->name('contract.partner-contract');
        Route::get('/contract/download-file/{id}', 'Contracts\ContractsController@downloadFile')->name('contract_stores.download');
        Route::get('/contract/show/{id}', 'Contracts\ContractsController@show')->name('contract.show');
        Route::get('partner/{id}/provide-category/', 'Partners\PartnersController@provideCategory')->name('partner.provide-category');
        Route::post('partner/{id}/provide-category/', 'Partners\PartnersController@updateProvideCategory')->name('partner.update-provide-category');
        Route::resource('partner', Partners\PartnersController::class);
        Route::resource('contract', Contracts\ContractsController::class);
        Route::resource('assets', Assets\AssetsController::class);
        Route::resource('category', Partners\CategoriesController::class);
        Route::get('group/import-excel', 'Partners\GroupsController@getImportForm')->name('group.get-import');
        Route::post('group/import-excel', 'Partners\GroupsController@postImport')->name('group.post-import');
        Route::resource('group', Partners\GroupsController::class);

        Route::post('/handover/branch-by-company/{id}', 'Assets\AssetHandoversController@getBranchByCompany');
        Route::post('/handover/get-department', 'Assets\AssetHandoversController@getDepartment');
        Route::post('/handover/get-user', 'Assets\AssetHandoversController@getUser');
        Route::post('/handover/active', 'Assets\AssetHandoversController@active')->name('handover.active');
        Route::post('/handover/active-store', 'Assets\AssetHandoversController@activeStore')->name('handover.active_store');
        Route::get('/handover/show/{id}', 'Assets\AssetHandoversController@show')->name('handover.show');
        Route::get('/handover/detail/{id}', 'Assets\AssetHandoversController@detail')->name('handover.detail');
        Route::post('/handover/cancel', 'Assets\AssetHandoversController@cancel')->name('handover.cancel');
        Route::post('/handover/get-asset-html', 'Assets\AssetHandoversController@getAssetHtml')->name('handover.get-asset-html');
        Route::get('/handover/history-structure/{structure_id}', 'Assets\AssetHandoversController@getHistoryStructure')->name('handover.get-history-structure');

        Route::resource('handover', Assets\AssetHandoversController::class);

        Route::get('/history/{id}', 'Assets\AssetHandoverHistoryController@index')->name('assets.history');
        Route::post('/repair/count-asset', 'Assets\AssetAssetsHistoriesController@countAsset');
        Route::post('/repair/update-status', 'Assets\AssetAssetsHistoriesController@updateStatus');
        Route::resource('repair', Assets\AssetAssetsHistoriesController::class);
        Route::get('imports/import-excel', 'Assets\AssetImportsController@getImportExcelForm')->name('imports.get-import');
        Route::post('imports/import-excel', 'Assets\AssetImportsController@postImportExcel')->name('imports.post-import');
        Route::resource('imports', Assets\AssetImportsController::class);
        Route::resource('units', Assets\UnitsController::class);

        Route::get('/reports/export', 'Reports\AssetsReportsController@export')->name('reports.export');
        Route::resource('reports', Reports\AssetsReportsController::class);

    });
    Route::group(['prefix' => 'invest'], function () {
        Route::get('/package/list-contract/{id}', 'Invest\AssetPackagesController@getContractByPackage')->name('package.contract');
        Route::get('/package/add-contract/{id}', 'Invest\AssetPackagesController@addContractByPackage')->name('package.add-contract');
        Route::post('/package/add-contract', 'Invest\AssetPackagesController@addContract')->name('package.add-contract');
        Route::post('/package/delete-contract', 'Invest\AssetPackagesController@deleteContract')->name('package.delete-contract');

app/Http/Controllers/Systems/CompaniesController.php
<?php

namespace App\Http\Controllers\Systems;

use App\Criteria\DeleteRelationCriteria;
use App\Http\Controllers\Controller;
use App\Models\Documents\Documents;
use App\Models\Systems\Company;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Auth;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\Systems\CompanyCreateRequest;
use App\Http\Requests\Systems\CompanyUpdateRequest;
use App\Repositories\Systems\CompanyRepository;
use App\Validators\Systems\CompanyValidator;

/**
 * Class CompaniesController.
 *
 * @package namespace App\Http\Controllers\Systems;
 */
class CompaniesController extends Controller
{
    /**
     * @var CompanyRepository
     */
    protected $repository;

    /**
     * @var CompanyValidator
     */
    protected $validator;

    private $partView;

    /**
     * CompaniesController constructor.
     *
     * @param CompanyRepository $repository
     * @param CompanyValidator $validator
     */
    public function __construct(CompanyRepository $repository, CompanyValidator $validator)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
        $this->partView = 'administrator.systems.company';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $companies = $this->repository->paginate();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $companies,
            ]);
        }

        return view($this->partView.'.index', ['data' => $companies]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CompanyCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(CompanyCreateRequest $request)
    {
        try {
            $model   = $this->repository->model();
            $input   = $request->all();
            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);
            $input[$model::CREATED_BY] = Auth::user()->id;

            $company = $this->repository->create($input);

            $logo = $request->file_logo;
            $partner['logo'] = $logo;
            $company->save();

            $response = [
                'message' => trans('messages.create_success'),
                'data'    => $company->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }
            return redirect()->route('company.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = $this->repository->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $company,
            ]);
        }

        return view('companies.show', compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = $this->repository->find($id);

        return view($this->partView.'.edit', ['data' => $company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  CompanyUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(CompanyUpdateRequest $request, $id)
    {
        try {
            $input = $request->all();
            $this->validator->with($input)->passesOrFail(ValidatorInterface::RULE_UPDATE);
            $request['updated_by'] = Auth::user()->id;

            $company = $this->repository->update($input, $id);

            $logo = $request->file_logo;
            $partner['logo'] = $logo;
            $company->save();

            $response = [
                'message' => trans('messages.update_success'),
                'data'    => $company->toArray(),
            ];
            if ($request->wantsJson()) {

                return response()->json($response);
            }
            return redirect()->route('company.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }
            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {
            return response()->json([
                'message' => trans('messages.delete_success'),
                'deleted' => $deleted,
            ]);
        }
        return redirect()->route('company.index')->with('message', trans('messages.delete_success'));
    }

    public function create(){
        return view($this->partView.'.create');
    }

    public function postUploadAttachment(Request $request)
    {
        $file = $request->file;
        $attachment[Documents::URL] = uploadFile($file, IMAGE_COMPANY);
        $attachment[Documents::MODEL_NAME] = 'Company';
        $attachment[Documents::NAME] = $file->getClientOriginalName();

        $obj = Documents::create($attachment);
        $this->listImage[] = $obj->id;

        return response()->json([
            'message' => trans('messages.upload_success'),
            'data' => $obj,
        ]);
    }

    public function postDeleteAttachment(Request $request)
    {
        $file = $request->all();
        $data = Documents::find($file['id']);
        if ($data) {
            $data->delete();
            unlink(public_path() . $file['url']);
        };
        return response()->json([
            'message' => trans('messages.delete_success'),
            'status' => true,
        ]);
    }
}

resources/views/administrator/systems/position/create.blade.php
@extends('administrator.app')
@section('title','Thêm mới vị trí')

@section('content')
<div class="container">
    <div class="list-content">
        <div class="wrap-title">
            <h2 class="title_list">Thêm mới vị trí</h2>
        </div>
        @include('administrator.errors.errors-validate')
        {{ Form::open(array('route' => 'position.store', 'class' => '')) }}
            <section class="main-content-add">
                <div class="row">
                    <div class="wrap-title">
                        <h3 class="sub_title">Thông tin cơ bản</h3>
                    </div>
                    <div class="col-lg-9 col-md-9 col-xs-12">
                        <div class="form-group">
                            <label for="name">
                                Tên: <span class="required">(*)</span>
                            </label>
                            <input type="name" class="form-control m-input" id="name" placeholder="Tên vị trí" name="name" value="{{ old('name') }}">
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-xs-12">
                        <div class="form-group">

                        </div>
                    </div>
                </div>
            </section>
            <section class="button">
                <div class="m-portlet__foot m-portlet__foot--fit" style="text-align: right;">
                    <div class="m-form__actions">
                        <div class="container">
                            <div class="row">
                                <div class="offset-md-6 col-lg-3 col-md-3 col-xs-12">
                                    <button type="submit" class="save_bid">
                                        Lưu
                                    </button>
                                </div>
                                <div class="col-lg-3 col-md-3 col-xs-12">
                                    <a class="delete_bid" href="{{ route('position.index') }}">
                                        Trở về danh sách
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        {{ Form::close() }}
    </div>
</div>
@stop

resources/views/administrator/systems/position/edit.blade.php
@extends('administrator.app')
@section('title',' vị trí')

@section('content')
    <div class="container">
        <div class="list-content">
            <div class="wrap-title">
                <h2 class="title_list">Thêm mới vị trí</h2>
            </div>
            @include('administrator.errors.errors-validate')
            {{ Form::open(array('route' => array('position.update', $data->id),
            'method' => 'PUT', 'class' => '')) }}
            <section class="main-content-add">
                <div class="row">
                        <div class="wrap-title">
                            <h3 class="sub_title">Thông tin cơ bản</h3>
                        </div>
                        <div class="col-lg-9 col-md-9 col-xs-12">
                            <div class="form-group">
                                <label for="name">
                                    Tên: <span class="required">(*)</span>
                                </label>
                                <input type="name" class="form-control m-input" id="name" placeholder="Tên vị trí" name="name" value="{{ $data->name }}">
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-xs-12">
                            <div class="form-group">

                            </div>
                        </div>
                    </div>
            </section>
            <section class="button">
                <div class="m-portlet__foot m-portlet__foot--fit" style="text-align: right;">
                    <div class="m-form__actions">
                        <div class="row">
                                <div class="col-lg-3 col-md-3 col-xs-12">
                                    <button type="submit" class="save_bid">
                                        Lưu
                                    </button>
                                </div>
                                <div class="col-lg-3 col-md-3 col-xs-12">
                                    <a class="delete_bid" href="{{ route('position.index') }}">
                                        Trở về danh sách
                                    </a>
                                </div>
                            </div>
                    </div>
                </div>
            </section>
            {{ Form::close() }}
        </div>
    </div>
@stop

resources/views/administrator/systems/position/index.blade.php
@extends('administrator.app')
@section('title','Danh sách các vị trí')

@section('content')
    <div class="container">
        <div class="list-content">
        <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12" style="margin-bottom: 20px">
                    <h2 class="title_list">Danh sách các vị trí</h2>
                </div>
                <div class="cocol-lg-12 col-md-12 col-xs-12">
                    <a href="{{ route('position.create') }}" class="btn m-btn m-btn--icon btn-add-color">
                        <span>
                            <i class="fa flaticon-plus"></i>
                            <span>
                                Thêm mới
                            </span>
                        </span>
                    </a>
                </div>
            </div>
        <section class="main-content">
            <div class="wrap-table">
                @include('administrator.errors.messages')
                <table class="table table-hover table-responsive table-striped">
                    <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">Tên</th>
                        <th scope="col">Tùy chọn</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($data as $key => $value)
                        <tr class="header expand">
                            <td scope="row">{{ $key + 1 }}</td>
                            <td>
                                {{ $value->name }}
                            </td>
                            <td>
                                <a href="{{ route('position.edit', $value->id) }}" class="">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                </a>
                                {{ Form::open(array('method'=>'DELETE', 'route' => array('position.destroy', $value->id), 'style' => 'display: inline-block;')) }}
                                <button onclick="return confirm('Bạn có chắc chắn muốn xóa?');" class="btn-delete">
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </button>
                                {{ Form::close() }}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <div class="wrap-title">
                {{ $data->links() }}
                Tổng số {{ $data->total() }} bản ghi
            </div>
        </section>
    </div>
    </div>
@stop