routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('login');
});
Route::get('administrator/login', ['uses' => 'Auth\AuthsController@getLogin'])->name('login');
Route::post('administrator/login', ['uses' => 'Auth\AuthsController@postLogin'])->name('login.post');
Route::post('administrator/register', ['uses' => 'Auth\AuthsController@postRegister'])->name('register');
Route::get('administrator/logout', ['uses' => 'Auth\AuthsController@getLogout'])->name('logout');
Route::get('user/activation/{token}', 'Auth\AuthsController@getActiveUser')->name('user.activate');
Route::post('user/forgot', 'Auth\AuthsController@postForgot')->name('user.forgot');
Route::get('/reset-password/{token}', 'Auth\AuthsController@getResetPassword')->name('user.reset');
Route::post('/reset-password', 'Auth\AuthsController@postResetPassword')->name('user.post-reset');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function () {
    Route::group(['prefix' => 'system'], function () {
        Route::resource('position', Systems\PositionsController::class);
        Route::get('user/user-department/{id}', 'Users\UsersController@getUserByDepartment')->name('user.list-user-by-department');
        Route::post('user/import', 'Users\UsersController@postImport')->name('user.import');
        Route::post('role/import', 'Permissions\RolesController@postImport')->name('role.import');
        Route::post('user/change-password', 'Users\UsersController@postChangePassword')->name('user.post-change-password');
        Route::get('/user/list', 'Users\UsersController@getList');
        Route::get('/user/change-password', 'Users\UsersController@getChangePassword')->name('user.get-change-password');
        Route::get('/user/be-managed', 'Users\UsersController@getBeManaged');
        Route::get('/user/search', 'Users\UsersController@getSearch');
        Route::post('/user/{id}', 'Users\UsersController@destroy');
        Route::get('/user/read-notification/{id}', 'Users\UsersController@readNotification')->name('user.read.notification');
        Route::get('/user/get-structure/{company}', 'Users\UsersController@getStructureByCompany')->name('user.get-structure');
        Route::resource('user', Users\UsersController::class);

        Route::post('company/{company}/structure/post-index', 'Systems\StructureCompaniesController@postIndex')->name('structure.post-index');
        Route::post('company/{company}/structure/delete', 'Systems\StructureCompaniesController@postDelete')->name('structure.delete');
        Route::get('company/{company}/structure/edit/{id}', 'Systems\StructureCompaniesController@getEdit');
        Route::post('company/{company}/structure/edit', 'Systems\StructureCompaniesController@postEdit')->name('structure.edit-post');
        Route::get('company/{company}/structure', 'Systems\StructureCompaniesController@index')->name('structure.index');
        Route::post('company/{company}/structure', 'Systems\StructureCompaniesController@store')->name('structure.store');
        Route::post('/company/attachment', 'Systems\CompaniesController@postUploadAttachment')->name('company.upload-attachment');
        Route::delete('/company/attachment', 'Systems\CompaniesController@postDeleteAttachment')->name('company.delete-attachment');
        Route::resource('company', Systems\CompaniesController::class);
        Route::resource('role', Permissions\RolesController::class);
        Route::resource('permission', Permissions\PermissionsController::class);
        Route::get('/config-role', 'Permissions\RolesController@getConfigRole')->name('role.config-role');
        Route::put('/put-permission', 'Permissions\RolesController@putPermissionIntoRole')->name('role.put-permission');
        Route::put('put-role', 'Permissions\RolesController@putRoleIntoUser')->name('role.put-role');
        Route::get('config-user', 'Permissions\RolesController@getConfigUser')->name('role.config-user');
        Route::get('permission-by-role', 'Permissions\RolesController@getPermissionByRole');
    });
    Route::group(['prefix' => 'asset'], function () {
        Route::get('district/{id}', 'Partners\PartnersController@getDistrictOnCity')->name('city.district.list');
        Route::get('dashboard', 'Assets\DashboardController@index')->name('asset.index');
        Route::post('/contract/attachment', 'Contracts\ContractsController@postUploadAttachment')->name('contract.upload-attachment');
        Route::delete('/contract/attachment', 'Contracts\ContractsController@postDeleteAttachment')->name('contract.delete-attachment');
        Route::post('/partner/attachment', 'Partners\PartnersController@postUploadAttachment')->name('partner.upload-attachment');
        Route::delete('/partner/attachment', 'Partners\PartnersController@postDeleteAttachment')->name('partner.delete-attachment');
        Route::get('/partner/download-file/{id}', 'Partners\PartnersController@downloadFile')->name('partner_stores.download');
        Route::post('/assets/attachment', 'Assets\AssetsController@postUploadAttachment')->name('asset.upload-attachment');
        Route::delete('/assets/attachment', 'Assets\AssetsController@postDeleteAttachment')->name('asset.delete-attachment');
        Route::get('/partner/search-partner', 'Partners\PartnersController@searchPartner')->name('partner.search-partner');
        Route::get('/contract/search-contract', 'Contracts\ContractsController@searchContract')->name('contract.search-contract');
        Route::get('/contract/partner-contract/{id}', 'Contracts\ContractsController@getPartnerContract')->name('contract.partner-contract');
        Route::get('/contract/download-file/{id}', 'Contracts\ContractsController@downloadFile')->name('contract_stores.download');
        Route::get('/contract/show/{id}', 'Contracts\ContractsController@show')->name('contract.show');
        Route::get('partner/{id}/provide-category/', 'Partners\PartnersController@provideCategory')->name('partner.provide-category');
        Route::post('partner/{id}/provide-category/', 'Partners\PartnersController@updateProvideCategory')->name('partner.update-provide-category');
        Route::resource('partner', Partners\PartnersController::class);
        Route::resource('contract', Contracts\ContractsController::class);
        Route::resource('assets', Assets\AssetsController::class);
        Route::resource('category', Partners\CategoriesController::class);
        Route::get('group/import-excel', 'Partners\GroupsController@getImportForm')->name('group.get-import');
        Route::post('group/import-excel', 'Partners\GroupsController@postImport')->name('group.post-import');
        Route::resource('group', Partners\GroupsController::class);

        Route::post('/handover/branch-by-company/{id}', 'Assets\AssetHandoversController@getBranchByCompany');
        Route::post('/handover/get-department', 'Assets\AssetHandoversController@getDepartment');
        Route::post('/handover/get-user', 'Assets\AssetHandoversController@getUser');
        Route::post('/handover/active', 'Assets\AssetHandoversController@active')->name('handover.active');
        Route::post('/handover/active-store', 'Assets\AssetHandoversController@activeStore')->name('handover.active_store');
        Route::get('/handover/show/{id}', 'Assets\AssetHandoversController@show')->name('handover.show');
        Route::get('/handover/detail/{id}', 'Assets\AssetHandoversController@detail')->name('handover.detail');
        Route::post('/handover/cancel', 'Assets\AssetHandoversController@cancel')->name('handover.cancel');
        Route::post('/handover/get-asset-html', 'Assets\AssetHandoversController@getAssetHtml')->name('handover.get-asset-html');
        Route::get('/handover/history-structure/{structure_id}', 'Assets\AssetHandoversController@getHistoryStructure')->name('handover.get-history-structure');

        Route::resource('handover', Assets\AssetHandoversController::class);

        Route::get('/history/{id}', 'Assets\AssetHandoverHistoryController@index')->name('assets.history');
        Route::post('/repair/count-asset', 'Assets\AssetAssetsHistoriesController@countAsset');
        Route::post('/repair/update-status', 'Assets\AssetAssetsHistoriesController@updateStatus');
        Route::resource('repair', Assets\AssetAssetsHistoriesController::class);
        Route::get('imports/import-excel', 'Assets\AssetImportsController@getImportExcelForm')->name('imports.get-import');
        Route::post('imports/import-excel', 'Assets\AssetImportsController@postImportExcel')->name('imports.post-import');
        Route::resource('imports', Assets\AssetImportsController::class);
        Route::resource('units', Assets\UnitsController::class);

        Route::get('/reports/export', 'Reports\AssetsReportsController@export')->name('reports.export');
        Route::resource('reports', Reports\AssetsReportsController::class);

    });
    Route::group(['prefix' => 'invest'], function () {
        Route::get('/package/list-contract/{id}', 'Invest\AssetPackagesController@getContractByPackage')->name('package.contract');
        Route::get('/package/add-contract/{id}', 'Invest\AssetPackagesController@addContractByPackage')->name('package.add-contract');
        Route::post('/package/add-contract', 'Invest\AssetPackagesController@addContract')->name('package.add-contract');
        Route::post('/package/delete-contract', 'Invest\AssetPackagesController@deleteContract')->name('package.delete-contract');
        Route::resource('package', Invest\AssetPackagesController::class);
        Route::resource('investment', Invest\InvestmentsController::class);

app/Models/Assets/AssetAssetsRelation.php
<?php

namespace App\Models\Assets;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class AssetAssetsRelation.
 *
 * @package namespace App\Models;
 */
class AssetAssetsRelation extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [];

}

app/Models/Assets/AssetLog.php
<?php

namespace App\Models\Assets;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class AssetLog.
 *
 * @package namespace App\Models;
 */
class AssetLog extends Model implements Transformable
{
    use TransformableTrait;

    const ASSET_ID    = 'asset_id';
    const CONTRACT_ID = 'contract_id';
    const PARTNER_ID  = 'partner_id';
    const PARAMS      = 'params';
    const CREATED_BY  = 'created_by';
    const UPDATED_BY  = 'updated_by';

    protected $table = 'asset_logs';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        self::ASSET_ID,
        self::CONTRACT_ID,
        self::PARTNER_ID,
        self::PARAMS,
        self::CREATED_BY,
        self::UPDATED_BY,
    ];


    protected $dates = ['deleted_at'];

    protected $casts = [
        'params' => 'array'
    ];

    public function asset()
    {
        return $this->belongsTo(Asset::class, 'asset_id', 'id');
    }
}

app/Http/Controllers/Assets/AssetAssetsRelationsController.php
<?php

namespace App\Http\Controllers\Assets;

use App\Http\Controllers\Controller;
use App\Http\Requests\Assets\AssetAssetsRelationCreateRequest;
use App\Http\Requests\Assets\AssetAssetsRelationUpdateRequest;
use App\Repositories\Assets\AssetAssetsRelationRepository;
use App\Validators\Assets\AssetAssetsRelationValidator;

use App\Http\Requests;
use Illuminate\Http\Response;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
/**
 * Class AssetAssetsRelationsController.
 *
 * @package namespace App\Http\Controllers;
 */
class AssetAssetsRelationsController extends Controller
{
    /**
     * @var AssetAssetsRelationRepository
     */
    protected $repository;

    /**
     * @var AssetAssetsRelationValidator
     */
    protected $validator;

    /**
     * AssetAssetsRelationsController constructor.
     *
     * @param AssetAssetsRelationRepository $repository
     * @param AssetAssetsRelationValidator $validator
     */
    public function __construct(AssetAssetsRelationRepository $repository, AssetAssetsRelationValidator $validator)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $assetAssetsRelations = $this->repository->all();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $assetAssetsRelations,
            ]);
        }

        return view('assetAssetsRelations.index', compact('assetAssetsRelations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  AssetAssetsRelationCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(AssetAssetsRelationCreateRequest $request)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $assetAssetsRelation = $this->repository->create($request->all());

            $response = [
                'message' => trans('messages.create_success'),
                'data'    => $assetAssetsRelation->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $assetAssetsRelation = $this->repository->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $assetAssetsRelation,
            ]);
        }

        return view('assetAssetsRelations.show', compact('assetAssetsRelation'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $assetAssetsRelation = $this->repository->find($id);

        return view('assetAssetsRelations.edit', compact('assetAssetsRelation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  AssetAssetsRelationUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(AssetAssetsRelationUpdateRequest $request, $id)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $assetAssetsRelation = $this->repository->update($request->all(), $id);

            $response = [
                'message' => trans('messages.update_success'),
                'data'    => $assetAssetsRelation->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => trans('messages.delete_success'),
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', trans('messages.delete_success'));
    }
}

app/Http/Controllers/Assets/DashboardController.php
<?php

namespace App\Http\Controllers\Assets;

use App\Http\Controllers\Controller;

class DashboardController extends Controller {

    public function index() {
        return view('administrator.dashboard');
    }

}

resources/views/administrator/assets/repair/create.blade.php
@extends('administrator.app')
@section('title','Thêm mới tài sản sửa chữa bảo hành')

@section('content')
    <div class="container">
        <div class="list-content">
            <div class="row">
                <div class="wrap-title">
                    <h2 class="title_list">
                        Thêm tài sửa chữa bảo hành
                    </h2>
                </div>
                <div class="col-lg-12 col-md-12 col-xs-12" style="margin-bottom: 20px;">
                    <a href="{{ route('repair.index') }}" class="btn m-btn m-btn--icon btn-add-color-cat">
                        Danh sách sửa chữa và bảo hành
                    </a>
                </div>
                <div class="col-lg-12 col-md-12 col-xs-12">
                    @include('administrator.errors.errors-validate')
                    @include('administrator.errors.messages')
                    <!--begin::Portlet-->
                        <div class="m-portlet m-portlet--tab">
                            <h3 class="sub_title">Thông tin cơ bản</h3>
                            {{ Form::open(array(
                            'route' => 'repair.store',
                            'class' => 'm-form m-form--fit m-form--label-align-right',
                             'files'=>true)) }}
                            <meta name="csrf-token" content="{{ csrf_token() }}">
                            <div class="row">
                                <div class="col-lg-3 col-md-3 col-xs-12">
                                    <div class="form-group m-form__group">
                                        <label for="name">
                                            Công ty<span class="required">(*)</span>
                                        </label>
                                        <select class="form-control m-input drl_person_company m-select2"
                                                name="company_owner">
                                            <option value="0">-- Chọn công ty --</option>
                                            @foreach ($listCompany as $key_l => $value_l)
                                                <option value="{{ $key_l }}"
                                                        {{(old("company_owner") == $key_l) ? 'selected':'' }} >
                                                    {{ $value_l }}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-xs-12">
                                    <div class="form-group m-form__group">
                                        <label for="name">
                                            Đơn vị trực thuộc công ty<span style="color: red;">(*)</span>
                                        </label>
                                        <select class="form-control m-input drl_person_structure m-select2" id="drl_person_structure"
                                                name="structure_owner">
                                            @if(old("company_owner"))
                                                <?php echo \App\Models\Systems\StructureCompany::genHtmlStructure(old("company_owner"), old("structure_owner")) ?>
                                            @endif
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-xs-12">
                                    <div class="form-group m-form__group">
                                        <label for="name">
                                            Người báo bảo hành<span class="required">(*)</span>
                                        </label>
                                        <input class="form-control m-input txt_people_notice" placeholder="Người thông báo"
                                               name="people_notice"
                                               value="{{old('people_notice')}}">
                                    </div>
                                </div>
                            </div>
                            <div class="m-portlet__body row" id="asset_repair">
                                <div class="col-lg-12 col-md-12 col-xs-12">
                                    <h3 class="sub_title" style="padding: 20px 0 20px 0;">
                                        Chi tiết sửa chữa
                                    </h3>
                                </div>
                                <div class="col-lg-12 col-md-12 col-xs-12">
                                    <div class="divTable blueTable">
                                        <div class="divTableHeading">
                                            <div class="divTableRow">
                                                <div class="divTableHead">Tên TS</div>
                                                <div class="divTableHead">Nhóm TS</div>
                                                <div class="divTableHead">TS hiện có</div>
                                                <div class="divTableHead">SL sửa chữa</div>
                                                <div class="divTableHead">Ngày bắt đầu</div>
                                                <div class="divTableHead">Ngày kết thúc</div>
                                                <div class="divTableHead">Đơn giá SC</div>
                                                <div class="divTableHead">Loại sửa chữa</div>
                                                <div class="divTableHead">Ghi chú</div>
                                            </div>
                                        </div>
                                        <div class="divTableBody handover_content_body"
                                             data-repeater-list="repair_content">

                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12 col-md-12 col-xs-12">
                                    <p class="add_contract" data-toggle="modal" data-target="#edit-modal">
                                        + Thêm nội dung sửa chữa
                                    </p>
                                </div>
                                @include('administrator.assets.handover.modal')
                            </div>
                            <section class="button">
                                <div class="m-portlet__foot m-portlet__foot--fit" style="text-align: right;">
                                    <div class="m-form__actions">
                                        <div class="container">
                                            <div class="row">
                                                <div class="offset-md-6 col-lg-3 col-md-3 col-xs-12">
                                                    <button type="submit" class="save_bid">
                                                        Lưu
                                                    </button>
                                                </div>
                                                <div class="col-lg-3 col-md-3 col-xs-12">
                                                    <a class="delete_bid" href="{{ route('repair.index') }}">
                                                        Trở về danh sách
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </section>
                            {{ Form::close() }}
                        </div>
                        <!--end::Portlet-->
                    </div>
                    <!--end::Form-->
                </div>
        </div>
    </div>
    @include('administrator.assets.repair.script')
@stop

resources/views/administrator/assets/repair/index.blade.php
@extends('administrator.app')
@section('title','Danh sách sửa chữa và bảo hành')

@section('content')
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <div class="container">
    <div class="list-content">
        <div class="wrap-title">
            <h2 class="title_list">
                <a href="{{ route('repair.index') }}">Danh sách sửa chữa và bảo hành</a>
            </h2>
        </div>
        <div class="wrap-title">
            <a href="{{ route('repair.create') }}" class="btn btn-primary m-btn m-btn--icon btn-add-color">
                <span>Thêm mới</span>
            </a>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-xs-12" style="padding-top:20px;">
                @include('administrator.errors.errors-validate')
                @include('administrator.errors.messages')
            </div>
        </div>
        <section class="main-content">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-xs-12">
                    <table class="table table-hover table-responsive table-striped">
                        <thead class="table_head">
                            <tr>
                                <th scope="col">STT</th>
                                <th scope="col">Tên TS</th>
                                <th scope="col">Mã nhóm TS</th>
                                <th scope="col">Đơn vị</th>
                                <th scope="col">Giá SC</th>
                                <th scope="col">Người báo SC/BH</th>
                                <th scope="col">Ngày tạo</th>
                                <th scope="col">Ghi chú</th>
                                <th scope="col">Trạng thái</th>
                                <th scope="col">Tùy chọn</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($data as $key => $value)
                            <tr class="header expand item_history_repair">
                                <td>{{ $key + 1 }}</td>
                                <td>{{ data_get($value, 'asset.name') }}</td>
                                <td>{{ data_get($value, 'asset.group.group_code') }}</td>
                                <td>
                                    {{ data_get($value, 'asset.ownerStructure.name') }}
                                </td>
                                <td>{{ @number_format($value->price_repair) }}</td>
                                <td>{{ @$value->people_notice }}</td>
                                <td>{{ @$value->created_at->format('d-m-Y') }}</td>
                                <td>{{ @$value->note }}</td>
                                <td>
                                    <select class="form-control m-input drl_history_status"
                                            name="status">
                                        @foreach (\App\Models\Assets\AssetAssetsHistory::$assetHistoryStatus as $key_s=>$value_s)
                                            <option value="{{ $key_s }}" {{($value->status == $key_s) ? 'selected':'' }} >
                                                {{ $value_s }}
                                            </option>
                                        @endforeach
                                    </select>
                                    <input type="hidden" value="{{$value->id}}" class="txt_history_id">
                                </td>
                                <td class="align-self-center">
                                    {{ Form::open(array('method'=>'DELETE', 'route' => array('repair.destroy', $value->id), 'style' => 'display: inline-block;')) }}
                                    <button onclick="return confirm('Bạn có chắc chắn muốn xóa?');"
                                            class="btn-border-none ">
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                                    </button>
                                    {{ Form::close() }}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            {{ $data->links() }}
            Tổng số {{ $data->total() }} bản ghi
        </section>
    </div>
    <script>
        $(document).ready(function () {
            $('.drl_history_status').on('change', function (e) {
                e.preventDefault();
                initUpdateStatus(this);
            });

        });

        function initUpdateStatus(that) {
            var status = $(that).val();
            var id = $(that).closest('.item_history_repair').find('.txt_history_id').val();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                url: './repair/update-status',
                cache: false,
                type: "post",
                data: {id: id, status: status},
                dataType: 'json',
                success: function (response) {
                    location.reload(true);
                },
                error: function (data) {

                }
            });
            return false;
        }

    </script>

@stop