routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('login');
});
Route::get('administrator/login', ['uses' => 'Auth\AuthsController@getLogin'])->name('login');
Route::post('administrator/login', ['uses' => 'Auth\AuthsController@postLogin'])->name('login.post');
Route::post('administrator/register', ['uses' => 'Auth\AuthsController@postRegister'])->name('register');
Route::get('administrator/logout', ['uses' => 'Auth\AuthsController@getLogout'])->name('logout');
Route::get('user/activation/{token}', 'Auth\AuthsController@getActiveUser')->name('user.activate');
Route::post('user/forgot', 'Auth\AuthsController@postForgot')->name('user.forgot');
Route::get('/reset-password/{token}', 'Auth\AuthsController@getResetPassword')->name('user.reset');
Route::post('/reset-password', 'Auth\AuthsController@postResetPassword')->name('user.post-reset');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::group(['prefix' => 'administrator', 'middleware' => 'auth'], function () {
    Route::group(['prefix' => 'system'], function () {
        Route::resource('position', Systems\PositionsController::class);
        Route::get('user/user-department/{id}', 'Users\UsersController@getUserByDepartment')->name('user.list-user-by-department');
        Route::post('user/import', 'Users\UsersController@postImport')->name('user.import');
        Route::post('role/import', 'Permissions\RolesController@postImport')->name('role.import');
        Route::post('user/change-password', 'Users\UsersController@postChangePassword')->name('user.post-change-password');
        Route::get('/user/list', 'Users\UsersController@getList');
        Route::get('/user/change-password', 'Users\UsersController@getChangePassword')->name('user.get-change-password');
        Route::get('/user/be-managed', 'Users\UsersController@getBeManaged');
        Route::get('/user/search', 'Users\UsersController@getSearch');
        Route::post('/user/{id}', 'Users\UsersController@destroy');
        Route::get('/user/read-notification/{id}', 'Users\UsersController@readNotification')->name('user.read.notification');
        Route::get('/user/get-structure/{company}', 'Users\UsersController@getStructureByCompany')->name('user.get-structure');
        Route::resource('user', Users\UsersController::class);

        Route::post('company/{company}/structure/post-index', 'Systems\StructureCompaniesController@postIndex')->name('structure.post-index');
        Route::post('company/{company}/structure/delete', 'Systems\StructureCompaniesController@postDelete')->name('structure.delete');
        Route::get('company/{company}/structure/edit/{id}', 'Systems\StructureCompaniesController@getEdit');
        Route::post('company/{company}/structure/edit', 'Systems\StructureCompaniesController@postEdit')->name('structure.edit-post');
        Route::get('company/{company}/structure', 'Systems\StructureCompaniesController@index')->name('structure.index');
        Route::post('company/{company}/structure', 'Systems\StructureCompaniesController@store')->name('structure.store');
        Route::post('/company/attachment', 'Systems\CompaniesController@postUploadAttachment')->name('company.upload-attachment');
        Route::delete('/company/attachment', 'Systems\CompaniesController@postDeleteAttachment')->name('company.delete-attachment');
        Route::resource('company', Systems\CompaniesController::class);
        Route::resource('role', Permissions\RolesController::class);
        Route::resource('permission', Permissions\PermissionsController::class);
        Route::get('/config-role', 'Permissions\RolesController@getConfigRole')->name('role.config-role');
        Route::put('/put-permission', 'Permissions\RolesController@putPermissionIntoRole')->name('role.put-permission');
        Route::put('put-role', 'Permissions\RolesController@putRoleIntoUser')->name('role.put-role');
        Route::get('config-user', 'Permissions\RolesController@getConfigUser')->name('role.config-user');
        Route::get('permission-by-role', 'Permissions\RolesController@getPermissionByRole');
    });
    Route::group(['prefix' => 'asset'], function () {
        Route::get('district/{id}', 'Partners\PartnersController@getDistrictOnCity')->name('city.district.list');
        Route::get('dashboard', 'Assets\DashboardController@index')->name('asset.index');
        Route::post('/contract/attachment', 'Contracts\ContractsController@postUploadAttachment')->name('contract.upload-attachment');
        Route::delete('/contract/attachment', 'Contracts\ContractsController@postDeleteAttachment')->name('contract.delete-attachment');
        Route::post('/partner/attachment', 'Partners\PartnersController@postUploadAttachment')->name('partner.upload-attachment');
        Route::delete('/partner/attachment', 'Partners\PartnersController@postDeleteAttachment')->name('partner.delete-attachment');
        Route::get('/partner/download-file/{id}', 'Partners\PartnersController@downloadFile')->name('partner_stores.download');
        Route::post('/assets/attachment', 'Assets\AssetsController@postUploadAttachment')->name('asset.upload-attachment');
        Route::delete('/assets/attachment', 'Assets\AssetsController@postDeleteAttachment')->name('asset.delete-attachment');
        Route::get('/partner/search-partner', 'Partners\PartnersController@searchPartner')->name('partner.search-partner');
        Route::get('/contract/search-contract', 'Contracts\ContractsController@searchContract')->name('contract.search-contract');
        Route::get('/contract/partner-contract/{id}', 'Contracts\ContractsController@getPartnerContract')->name('contract.partner-contract');
        Route::get('/contract/download-file/{id}', 'Contracts\ContractsController@downloadFile')->name('contract_stores.download');
        Route::get('/contract/show/{id}', 'Contracts\ContractsController@show')->name('contract.show');
        Route::get('partner/{id}/provide-category/', 'Partners\PartnersController@provideCategory')->name('partner.provide-category');
        Route::post('partner/{id}/provide-category/', 'Partners\PartnersController@updateProvideCategory')->name('partner.update-provide-category');
        Route::resource('partner', Partners\PartnersController::class);
        Route::resource('contract', Contracts\ContractsController::class);
        Route::resource('assets', Assets\AssetsController::class);
        Route::resource('category', Partners\CategoriesController::class);
        Route::get('group/import-excel', 'Partners\GroupsController@getImportForm')->name('group.get-import');
        Route::post('group/import-excel', 'Partners\GroupsController@postImport')->name('group.post-import');
        Route::resource('group', Partners\GroupsController::class);

        Route::post('/handover/branch-by-company/{id}', 'Assets\AssetHandoversController@getBranchByCompany');
        Route::post('/handover/get-department', 'Assets\AssetHandoversController@getDepartment');
        Route::post('/handover/get-user', 'Assets\AssetHandoversController@getUser');
        Route::post('/handover/active', 'Assets\AssetHandoversController@active')->name('handover.active');
        Route::post('/handover/active-store', 'Assets\AssetHandoversController@activeStore')->name('handover.active_store');
        Route::get('/handover/show/{id}', 'Assets\AssetHandoversController@show')->name('handover.show');
        Route::get('/handover/detail/{id}', 'Assets\AssetHandoversController@detail')->name('handover.detail');
        Route::post('/handover/cancel', 'Assets\AssetHandoversController@cancel')->name('handover.cancel');
        Route::post('/handover/get-asset-html', 'Assets\AssetHandoversController@getAssetHtml')->name('handover.get-asset-html');
        Route::get('/handover/history-structure/{structure_id}', 'Assets\AssetHandoversController@getHistoryStructure')->name('handover.get-history-structure');

        Route::resource('handover', Assets\AssetHandoversController::class);

        Route::get('/history/{id}', 'Assets\AssetHandoverHistoryController@index')->name('assets.history');
        Route::post('/repair/count-asset', 'Assets\AssetAssetsHistoriesController@countAsset');
        Route::post('/repair/update-status', 'Assets\AssetAssetsHistoriesController@updateStatus');
        Route::resource('repair', Assets\AssetAssetsHistoriesController::class);
        Route::get('imports/import-excel', 'Assets\AssetImportsController@getImportExcelForm')->name('imports.get-import');
        Route::post('imports/import-excel', 'Assets\AssetImportsController@postImportExcel')->name('imports.post-import');
        Route::resource('imports', Assets\AssetImportsController::class);
        Route::resource('units', Assets\UnitsController::class);

        Route::get('/reports/export', 'Reports\AssetsReportsController@export')->name('reports.export');
        Route::resource('reports', Reports\AssetsReportsController::class);

    });
    Route::group(['prefix' => 'invest'], function () {
        Route::get('/package/list-contract/{id}', 'Invest\AssetPackagesController@getContractByPackage')->name('package.contract');
        Route::get('/package/add-contract/{id}', 'Invest\AssetPackagesController@addContractByPackage')->name('package.add-contract');
        Route::post('/package/add-contract', 'Invest\AssetPackagesController@addContract')->name('package.add-contract');
        Route::post('/package/delete-contract', 'Invest\AssetPackagesController@deleteContract')->name('package.delete-contract');

app/Models/Assets/AssetAssetsRelation.php
<?php

namespace App\Models\Assets;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class AssetAssetsRelation.
 *
 * @package namespace App\Models;
 */
class AssetAssetsRelation extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [];

}

app/Models/Assets/AssetLog.php
<?php

namespace App\Models\Assets;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class AssetLog.
 *
 * @package namespace App\Models;
 */
class AssetLog extends Model implements Transformable
{
    use TransformableTrait;

    const ASSET_ID    = 'asset_id';
    const CONTRACT_ID = 'contract_id';
    const PARTNER_ID  = 'partner_id';
    const PARAMS      = 'params';
    const CREATED_BY  = 'created_by';
    const UPDATED_BY  = 'updated_by';

    protected $table = 'asset_logs';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        self::ASSET_ID,
        self::CONTRACT_ID,
        self::PARTNER_ID,
        self::PARAMS,
        self::CREATED_BY,
        self::UPDATED_BY,
    ];


    protected $dates = ['deleted_at'];

    protected $casts = [
        'params' => 'array'
    ];

    public function asset()
    {
        return $this->belongsTo(Asset::class, 'asset_id', 'id');
    }
}

app/Http/Controllers/Assets/AssetAssetsRelationsController.php
<?php

namespace App\Http\Controllers\Assets;

use App\Http\Controllers\Controller;
use App\Http\Requests\Assets\AssetAssetsRelationCreateRequest;
use App\Http\Requests\Assets\AssetAssetsRelationUpdateRequest;
use App\Repositories\Assets\AssetAssetsRelationRepository;
use App\Validators\Assets\AssetAssetsRelationValidator;

use App\Http\Requests;
use Illuminate\Http\Response;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
/**
 * Class AssetAssetsRelationsController.
 *
 * @package namespace App\Http\Controllers;
 */
class AssetAssetsRelationsController extends Controller
{
    /**
     * @var AssetAssetsRelationRepository
     */
    protected $repository;

    /**
     * @var AssetAssetsRelationValidator
     */
    protected $validator;

    /**
     * AssetAssetsRelationsController constructor.
     *
     * @param AssetAssetsRelationRepository $repository
     * @param AssetAssetsRelationValidator $validator
     */
    public function __construct(AssetAssetsRelationRepository $repository, AssetAssetsRelationValidator $validator)
    {
        $this->repository = $repository;
        $this->validator  = $validator;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $assetAssetsRelations = $this->repository->all();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $assetAssetsRelations,
            ]);
        }

        return view('assetAssetsRelations.index', compact('assetAssetsRelations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  AssetAssetsRelationCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(AssetAssetsRelationCreateRequest $request)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $assetAssetsRelation = $this->repository->create($request->all());

            $response = [
                'message' => trans('messages.create_success'),
                'data'    => $assetAssetsRelation->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $assetAssetsRelation = $this->repository->find($id);

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $assetAssetsRelation,
            ]);
        }

        return view('assetAssetsRelations.show', compact('assetAssetsRelation'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $assetAssetsRelation = $this->repository->find($id);

        return view('assetAssetsRelations.edit', compact('assetAssetsRelation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  AssetAssetsRelationUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(AssetAssetsRelationUpdateRequest $request, $id)
    {
        try {

            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $assetAssetsRelation = $this->repository->update($request->all(), $id);

            $response = [
                'message' => trans('messages.update_success'),
                'data'    => $assetAssetsRelation->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => trans('messages.delete_success'),
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', trans('messages.delete_success'));
    }
}

app/Http/Controllers/Assets/DashboardController.php
<?php

namespace App\Http\Controllers\Assets;

use App\Http\Controllers\Controller;

class DashboardController extends Controller {

    public function index() {
        return view('administrator.dashboard');
    }

}

resources/views/administrator/assets/index.blade.php
@extends('administrator.app')
@section('title','Danh sách tài sản và công cụ')

@section('content')
    <div class="container">
        <div class="list-content">
            <div class="wrap-title">
                <h2 class="title_list">
                    <a href="{{ route('assets.index') }}">Danh sách tài sản và công cụ</a>
                </h2>
            </div>
            @include('administrator.errors.messages')
            @include('administrator.assets.search-asset')
            <section class="main-content">
                <div class="wrap-table">
                    <table class="table table-hover table-responsive table-striped">
                        <thead class="table_head">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Tên</th>
                            <th scope="col">Mã</th>
                            <th scope="col">Mã nhóm</th>
                            <th scope="col">Số hiệu HĐ</th>
                            <th scope="col">Chất liệu</th>
                            <th scope="col">Màu sắc</th>
                            <th scope="col">Số lượng</th>
                            <th scope="col">Đơn vị tính</th>
                            <th scope="col">Giá trị(VND)</th>
                            <th scope="col">Đơn vị SD</th>
                            <th scope="col">Người nhập kho</th>
                            <th scope="col">Ngày nhập kho</th>
                            <th scope="col">Phân loại</th>
                            <th scope="col">Bảo hành(tháng)</th>
                            <th scope="col">Năm sử dụng</th>
                            <th scope="col">Tình trạng</th>
                            <th scope="col">Tùy chọn</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($data as $key => $value)
                            <tr class="header">
                                <td scope="row">{{@$key +1}}</td>
                                <td class="text-left">{{ $value->name }}</td>
                                <td class="text-left">{{(isset($value->group->group_code)? $value->group->group_code.'-':'').$value->id }}</td>
                                <td class="text-left">{{ data_get($value, 'group.group_code') }}</td>
                                <td class="text-left">{{ @$value->contract_code }}</td>
                                <td class="text-left">{{ $value->material }}</td>
                                <td class="text-left">{{ $value->color }}</td>
                                <?php
                                $unit_lower = mb_strtolower(trim_all(data_get($value, 'unit.name')), 'UTF-8');
                                ?>
                                @if (in_array($unit_lower, UNIT_MEASUREMENT))
                                    <td class="text-right">{{ $value->quantity }}</td>
                                @else
                                    <td class="text-right">{{ number_format($value->quantity) }}</td>
                                @endif
                                <td class="text-left">{{ data_get($value, 'unit.name') }}</td>
                                <td class="text-right">{{ number_format($value->price) }}</td>
                                <td class="text-center">{{ data_get($value, 'ownerStructure.name') }}</td>
                                <td class="text-left">{{ $value->receiver_handover }}</td>
                                <td class="text-left">
                                    {{ isset($value->date_import)?
                                    Carbon\Carbon::createFromFormat('Y-m-d',$value->date_import)->format('d-m-Y'):''  }}
                                </td>
                                <td class="text-center">{{ isset($value->type) ?
                                    \App\Models\Assets\Asset::$assetClassification[$value->type] : 'Chưa phân loai' }}</td>
                                <td class="text-center">{{ $value->warranty }}</td>
                                <td class="text-center">{{ isset($value->year_use) ? $value->year_use : 'Chưa có' }}</td>
                                <td class="text-center">
                                    {{(isset($value->status) && $value->status) ?
                                    \App\Models\Assets\Asset::$assetListStatus[$value->status]: '' }}
                                </td>
                                <td>
                                    @if(isset($value->assetLog->id))
                                        <a href="{{ route('assets.history', $value->id) }}" class="">
                                            <i class="fa fa-history" aria-hidden="true"></i>
                                        </a>
                                    @endif
                                    <a href="{{ route('assets.edit', $value->id) }}" class="">
                                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                    </a>
                                    {{ Form::open(array('method'=>'DELETE', 'route' => array('assets.destroy', $value->id), 'style' => 'display: inline-block;')) }}
                                    <button onclick="return confirm('Bạn có chắc chắn muốn xóa?');"
                                            class="btn-delete">
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                                    </button>
                                    {{ Form::close() }}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="wrap-title">
                    {{ $data->appends($input)->links() }}
                    Tổng số {{ $data->total() }} bản ghi
                </div>
            </section>
        </div>
    </div>
@stop

resources/views/administrator/assets/search-asset.blade.php
{{ Form::open(array('route' => 'assets.index', 'method' => 'GET')  ) }}
<meta name="csrf-token" content="{{ csrf_token() }}">
<div class="row gutter-2 gutter-lg-3 mb-4">
    <div class="col-lg-3">
        <div class="form-group m-form__group">
            <label for="name">
                Tên
            </label>
            <input name="name" class="form-control m-input" placeholder="Tên tài sản"
                   value="{{isset($input['name'])?$input['name']:''}}"
            >
        </div>
    </div>
    <div class="col-lg-3">
        <div class="form-group m-form__group">
            <label for="name">
                Nhóm tài sản
            </label>
            <?php $selected = isset($input['group_id']) ? $input['group_id'] : '' ?>
            <select class="form-control m-input drl_group m-select2"
                    name="group_id">
                <option value="0">-- Tất cả --</option>
                <?php echo \App\Models\Partners\Group::genHtmlGroup($selected) ?>
            </select>

        </div>
    </div>
    <div class="col-lg-3">
        <div class="form-group m-form__group">
            <label for="name">
                Phân loại
            </label>
            <select class="form-control m-input drl_type m-select2"
                    name="type_id">
                <option value="">-- Tất cả --</option>
                @foreach (\App\Models\Assets\Asset::$assetClassification as $key_tp => $value_tp)
                    <option value="{{ $key_tp }}"
                            {{(isset($input['type_id']) && $input['type_id'] == $key_tp) ? 'selected':'' }}
                    >
                        {{ $value_tp }}
                    </option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="form-group m-form__group">
            <label for="name">
                Trạng thái
            </label>
            <select class="form-control m-input drl_status m-select2"
                    name="status">
                <option value="">-- Tất cả --</option>
                @foreach (\App\Models\Assets\Asset::$assetListStatus as $key_st => $value_st)
                    <option value="{{ $key_st }}"
                            {{(isset($input['status']) && $input['status'] == $key_st) ? 'selected':'' }}
                    >
                        {{ $value_st }}
                    </option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="form-group m-form__group">
            <label for="name">
                Trạng thái ban đầu
            </label>
            <select class="form-control m-input drl_status m-select2"
                    name="original">
                <option value="">-- Tất cả --</option>
                @foreach (\App\Models\Assets\Asset::$assetOriginalClassification as $key_st => $value_st)
                    <option value="{{ $key_st }}"
                            {{(isset($input['original']) && $input['original'] == $key_st) ? 'selected':'' }}
                    >
                        {{ $value_st }}
                    </option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="form-group m-form__group">
            <label for="name">
                Nhà thầu
            </label>
            <input name="name_partner" class="form-control m-input" placeholder="Tên nhà thầu">
        </div>
    </div>
    <div class="col-lg-3">
        <div class="form-group m-form__group">
            <label for="name">
                Công ty
            </label>
            <select class="form-control m-input drl_company_owner m-select2"
                    name="company_owner">
                <option value="0">-- Tất cả --</option>
                @foreach ($listCompany as $key_cp => $value_cp)
                    <option value="{{ $key_cp }}"
                            {{(isset($input['company_owner']) && $input['company_owner'] == $key_cp) ? 'selected':'' }}
                    >
                        {{ $value_cp }}
                    </option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="form-group m-form__group">
            <label for="name">
                Đơn vị trực thuộc công ty
            </label>
            <select class="form-control m-input drl_structure_owner m-select2"
                    name="structure_owner">
                @if($list_structure)
                    <option value="">-- Chọn đơn vị trực thuộc --</option>
                    @foreach($list_structure as $key_str => $val_str)
                        <option value="{{ $val_str['id'] }}"
                                {{(isset($input['structure_owner']) && $input['structure_owner'] == $val_str['id']) ? 'selected':'' }}
                        >
                            {{ $val_str['name']. ' | ' . \App\Models\Systems\StructureCompany::$listType[$val_str['type']]  }}
                        </option>
                    @endforeach
                @endif
            </select>
        </div>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-6 mb-3 mb-md-0">
        <input type="submit" class="form-control" id="search-button"
               value="Tìm kiếm" style="background: #f6811f;color: #fff;" data-action="{{route('assets.index')}}">
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 mb-3 mb-md-0">
        <div class="dropdown">
            <button class="dropdown-toggle_button btn-add-color btn m-btn m-btn--icon" type="button"
                    id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                Tùy chọn thêm mới
            </button>
            <div class="dropdown-menu drowdown-addnew" aria-labelledby="dropdownMenuButton">
                <a href="{{ route('units.index') }}" class="dropdown-item">
                    Danh sách đơn vị tính
                </a>
                <a href="{{ route('group.index') }}" class="dropdown-item">
                    Danh sách nhóm tài sản
                </a>
                <a href="{{ route('imports.create') }}" class="dropdown-item">
                    Thêm mới tài sản
                </a>
            </div>
        </div>
    </div>
</div>
{{ Form::close() }}